project:
  type: website

website:
  title: "The Fredston Lab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: about.qmd
      - text: Lab members
        href: members.qmd
      - text: Join the lab
        href: join.qmd
      - text: Support the lab
        href: support.qmd
#      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

